name: Quality Assurance
on: [pull_request, workflow_call]

jobs:
  quality-assurance:
    name: Quality Assurance
    runs-on: ubuntu-latest
    container: python:3.10.4-buster

    services:
      db:
        image: postgres:14.2-alpine
        env:
          POSTGRES_DB: cooking_core
          POSTGRES_USER: cooking_core
          POSTGRES_PASSWORD: cooking_core

    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.2

      - name: Install Dependencies
        run: make install && make install-pre-commit

      - name: Lint
        run: make lint

      - name: Test
        run: make test
        env:
          COOKING_CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'
          COOKING_CORE_SETTING_LOCAL_SETTINGS_PATH: "./{{cookiecutter.package_name}}/project/settings/templates/settings.github.py"
