# Generated by Django 5.0.2 on 2024-03-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OauthProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                ("secret", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[("google", "Google"), ("github", "Github")],
                        default="google",
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
