# Generated by Django 5.0.2 on 2024-03-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauthprovider",
            name="provider",
            field=models.CharField(
                choices=[("GOOGLE", "Google")], default="GOOGLE", max_length=100
            ),
        ),
    ]
