# Generated by Django 5.0.2 on 2024-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="body",
        ),
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("0", "Draft"), ("1", "Published")],
                default="0",
                max_length=100,
            ),
        ),
    ]
