# Generated by Django 5.0 on 2024-02-03 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
