# Generated by Django 5.0 on 2024-02-08 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='c_emails',
        ),
        migrations.RemoveField(
            model_name='task',
            name='download_code',
        ),
        migrations.RemoveField(
            model_name='task',
            name='i_emails',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='task',
            name='u_emails',
        ),
        migrations.RemoveField(
            model_name='task',
            name='v_emails',
        ),
        migrations.RemoveField(
            model_name='task',
            name='verified_emails',
        ),
    ]
