# Generated by Django 5.0.2 on 2024-02-24 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_task_c_emails_remove_task_download_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="file",
        ),
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
    ]
