# Generated by Django 5.0.2 on 2024-03-05 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_task_file_remove_task_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
