# Generated by Django 5.0.2 on 2024-03-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_blog_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="user",
        ),
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
