# Generated by Django 5.0.2 on 2024-03-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_social",
            field=models.BooleanField(default=False),
        ),
    ]
